package Structs

//CriminalLaw struct that contains possible matches with criminal law
var CriminalLaw = []string{
	"prestação pecuniária",
	"prestação de serviços à comunidade",
	"descaminho",
	"interrogatório",
	"atos executórios",
	"inquirição",
	"oitiva",
	"lesão corporal",
	"estelionato",
	"injúria",
	"difamação",
	"ameaça",
	"homicídio",
	"preso",
	"penal",
	"criminal",
	"inquérito",
	"inquerito",
	"pena",
	"juri",
	"corpus",
	"liberdade",
	"reclusão",
	"prisão",
	"prisao",
	"antitóxicos",
	"crime",
	"restituição de coisas",
	"termo circunstanciado",
	"maria da penh",
	"núm.caract(g153,)<>núm.caract(substituir(g153",
	"maria da penha",
	"crim",
	"proced.investigatório do mp",
	"detenção",
	"execução de medidas alternativas",
	"toxico",
	"indulto",
	"acusado",
	"pedido de quebra de sigilo de dados e/ou telefônic",
	"semi-aberto",
	"fechado",
	"aberto",
	"condicional",
	"furto",
	"roubo",
	"receptação",
	"latrocínio",
	"drogas",
	"apropriação indébita",
	"dano qualificad",
	"falso",
	"policial",
	"violência",
}
